[".local/share/zinit"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/zinit.git"
    refreshPeriod = "24h"
[".local/share/vim/bundle/Vundle.vim"]
    type = "git-repo"
    url = "https://github.com/VundleVim/Vundle.vim.git"
    refreshPeriod = "168h"
{{- if not (eq .chezmoi.os "darwin") }}
[".local/bin/argocd"]
    type = "file"
{{-   if eq .chezmoi.os "windows" }}
    url = "https://github.com/argoproj/argo-cd/releases/latest/download/argocd-windows-{{ .chezmoi.arch }}.exe"
{{-   else }}
    url = "https://github.com/argoproj/argo-cd/releases/latest/download/argocd-{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
{{-   end }}
    executable = true
    refreshPeriod = "168h"
{{- end }}


[".config/k9s/skin.yml"]
    type = "file"
    url = "https://raw.githubusercontent.com/derailed/k9s/master/skins/dracula.yml"
    refreshPeriod = "168h"
