tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "shivammathur/php"
brew "bash"
brew "bat"
brew "borgbackup"
brew "python@3.9"
brew "glib"
brew "pkg-config"
brew "php"
brew "composer"
brew "coreutils"
brew "deno"
brew "dnsmasq"
brew "exa"
brew "exiftool"
brew "findutils"
brew "folly"
brew "fzf"
brew "gh"
brew "git"
brew "gnu-sed"
brew "go"
brew "htop"
brew "imagemagick"
brew "jq"
brew "libusb"
brew "mailhog", restart_service: true
brew "mas"
brew "mysql", restart_service: true
brew "neofetch"
brew "nghttp2"
brew "nginx"
brew "nvm"
brew "php@7.4"
brew "postgresql", restart_service: true
brew "ripgrep"
brew "rsync"
brew "rustup-init"
brew "starship"
brew "tree"
brew "unzip"
brew "vim"
brew "watch"
brew "watchman"
brew "zip"
brew "zsh"
cask "1password-beta"
cask "adoptopenjdk"
cask "alfred"
cask "bitwarden"
cask "cleanmymac"
cask "discord"
cask "docker"
cask "forticlient-vpn"
cask "google-chrome"
cask "gpg-suite"
cask "iterm2"
cask "jetbrains-toolbox"
cask "microsoft-office"
cask "microsoft-teams"
cask "spotify"
cask "ultimaker-cura"
cask "visual-studio-code"
cask "vlc"
cask "vorta"
cask "whatsapp"
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
