[username]
show_always=true

[hostname]
ssh_only=false

[conda]
symbol = " "

[dart]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[julia]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

